### ISSUE TITLE
How to make ThemeSwitchAIO change the css class?

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [AnnMarieW/dash-bootstrap-templates#12]
Hi @AnnMarieW 

thanks for these useful templates! I am kinda new to all this 😄 

I would like to add a dark mode to [my web app](https://htm-dashboard.herokuapp.com/).

I added a `ThemeSwitchAIO` component to the layout (without changing the graph template yet).

It changes the default settings (background, primary colour, etc.) as expected. However, some of my components have custom css where the background colour is set to white. Also the dcc.Tabs component seems unaffected. See screenshots below.

surely there is something I'm not doing right.

Do you have any idea?

Thanks in advance for your support!

Remi

light mode
![image](https://user-images.githubusercontent.com/40028739/194053250-cd022a64-f436-493b-a95e-09c9660e0685.png)

"dark" mode
![image](https://user-images.githubusercontent.com/40028739/194053385-bee95cb6-ad94-405b-b550-4748a36ac87f.png)

**Comment by AnnMarieW** [comment]
Hi @RemDelaporteMathurin 

I'm glad you like the templates!  Sure, I can help you with this, but since this is a "how to" question and not a bug, it would be better to post this on the [Dash community forum](https://community.plotly.com).  I'll answer it there - and it's also a great way to show off your cool app :sunglasses: 

In the meantime, please check out my [Dash Bootstrap Theme Explorer](https://hellodash.pythonanywhere.com/) site.  It has lots of info on how to style your app with a Bootstrap theme.  To style dcc components see this section: https://hellodash.pythonanywhere.com/adding-themes/dcc-components
