### ISSUE TITLE
Data Table Pagination and Export Button not styled?

### ISSUE THREAD

**Issue by jlayt** [AnnMarieW/dash-bootstrap-templates#38]
The Data Table pagination and export button do not adopt the Bootstrap styling, but text does. Example shown here with Flatly theme. I've tried adding a class of dbc at both at the top Container level and in an enclosing Div as shown in the example, but neither works.

![Screenshot 2024-08-01 at 11 54 45](https://github.com/user-attachments/assets/d80cf291-1f14-4c0f-b39c-9bbdbad1edb0)

![Screenshot 2024-08-01 at 12 58 51](https://github.com/user-attachments/assets/bdc56f33-5af3-4510-b383-3f4281e23fa9)

**Comment by jlayt** [comment]
My apologies, further testing shows that the styles are not apply to any Dash components, in spite of the CSS downloading and the class beign correclty set. There must be something else going on with my code that is breaking things.

**Comment by jlayt** [comment]
Ah, not having a great day, getting myself confused... 

Recreated with a minimal example with Dropdowns and a DataTable wrapped in a container. Using dbc as class on the container the Bootstrap styles are applied to the Dropdowns but not to the DataTable buttons and pagination. The DataTable does get the fonts applied, and the cell borders and header background but they look broken.

Manually removing the dbc class from the container using Dev Tools removes the Bootstrap styling from all teh components, including the font styles and borders on the DataTable. Manually adding dbc again back restores the Bootstrap styles again.

With dbc class set on container:

![Screenshot 2024-08-01 at 15 50 46](https://github.com/user-attachments/assets/2d3301f1-1e2f-4805-b5e2-24908a311b99)

With dbc class removed from container:

![Screenshot 2024-08-01 at 15 50 26](https://github.com/user-attachments/assets/944c2149-2c3a-45aa-b253-b778094449cf)

Apologies for my confusion!

**Comment by AnnMarieW** [comment]
Hi @jlayt 

Styling that export button in the DataTable is tricky.  You can find a discussion and some workarounds on the forum   https://community.plotly.com/t/styling-the-export-button-in-datatable/38798/9

The solution from the forum would be good if you are not switching themes.  Since there is no general solution that works well with all Bootstrap themes, I haven't added this feature to  the `dbc` class here.

Another workaround is to add a clientside callback that adds a bootstrap class to the export button so it looks like this:
```
<button class="export btn btn-primary">Export</button>
```
That's a little tricky as well, since you have to make sure the table is rendered before adding the classes.  Let me know if you want to do this, and I might be able to help.

Another solution is to use dash-ag-grid.  You can add your own button to export the data.
- https://dash.plotly.com/dash-ag-grid/export-data-csv
- https://community.plotly.com/t/open-source-dash-ag-grid-excel-download/83567
- https://dashaggridexamples.pythonanywhere.com/import-export
