### ISSUE TITLE
themes fail to fully apply when persistence in enabled for radio_props of ThemeChangerAIO

### ISSUE THREAD

**Issue by mayushii21** [AnnMarieW/dash-bootstrap-templates#43]
Example ThemeChangerAIO:
```
ThemeChangerAIO(
    aio_id="theme",
    radio_props={
        "options": [
            {
                "label": "Cyborg",
                "value": dbc.themes.CYBORG,
                "label_id": "theme-switch-label-dark",
            },
            {
                "label": "Vapor",
                "value": dbc.themes.VAPOR,
                "label_id": "theme-switch-label-dark",
            }
        ],
        "value": dbc.themes.CYBORG,
        "persistence": True,
    }
)
```

On the first load, the Cyborg theme is rendered, as expected. Switching to Vapor properly switches the theme to Vapor. Reloading the page, however, results in a theme somewhere in between Vapor and Cyborg, where the background is Vapor, but the text color, button borders, and other elements are Cyborg.

In version 1.1.2, things work properly (persisted themes get correctly applied after reload), but only in Chrome, not in Firefox. After version 1.1.2 the issue is present in Chrome as well.

Here is how things should look after reload (same as when freshly applying the theme):
![image](https://github.com/user-attachments/assets/7f0e25a4-ba0c-4c0b-97bb-dd1a8a74ebca)
![image](https://github.com/user-attachments/assets/6c714dc1-d6e3-450f-884e-65af212d0168)
![image](https://github.com/user-attachments/assets/6ee2a52c-51cc-4565-b1ca-3d2c8870abcd)

Here is how they look after reloading with version 1.1.2 in Firefox, and in Chrome as well with newer versions:
![image](https://github.com/user-attachments/assets/7ba4625b-f1c3-4336-9b7c-eaf077fe8d10)
![image](https://github.com/user-attachments/assets/8f21b845-c2a9-4eec-815e-aa294595f627)
![image](https://github.com/user-attachments/assets/74976ec6-921d-43b5-8b30-0e276b6df99c)

**Comment by AnnMarieW** [comment]
Hi @mayushii21 
Thanks for reporting... I'm looking into it :thinking:

**Comment by mayushii21** [comment]
@AnnMarieW have you managed to reproduce the issue? I tested #44 and it completely broke themes for me.. With it, nothing at all applies, just a white background and broken page structure

**Comment by AnnMarieW** [comment]
Hi @mayushii21 

I’m traveling for a few days and haven’t had a chance to look at the PR yet.  In the meantime, it would be best to pin the version to 1.1.2.  Hopefully we will have a solution soon.

**Comment by sdidier-dev** [comment]
Hi @mayushii21!
You should have tagged me 😁
I knew there was one thing to fix in my PR, now that should be fine if you want to test it 😉

**Comment by sdidier-dev** [comment]
btw, you can remove "label_id", it's not used anymore with this version👍

**Comment by AnnMarieW** [comment]
@sdidier-dev Thanks for the update!   Is the removal of the `label_id` be a breaking change?

**Comment by sdidier-dev** [comment]
@AnnMarieW No, not a breaking change 😉 
The style is applied using the `style` param of the component to apply it inline, instead of using CSS
https://github.com/AnnMarieW/dash-bootstrap-templates/pull/44/files#diff-aa772a859774952fa50ae1d32486545cec00116dd58132f1f25a27860fd00c56R113-R120

I know that's from `dbc.RadioItems` but it looked weird to me to use the `id` as a `class` to apply CSS (there is not something like `label_class`, only `label_id`).

So no need to set `"label_id": "theme-switch-label-dark"` it's handled internally using the `dbc_dark_themes` list + the new param `custom_dark_themes` to apply the dark label style to custom themes

If someone is already using `"label_id": "theme-switch-label-dark"` in his app and uses this new `ThemeChangerAIO` it will have no effect 👍 

And we can remove the callback
https://github.com/AnnMarieW/dash-bootstrap-templates/pull/44/files#diff-aa772a859774952fa50ae1d32486545cec00116dd58132f1f25a27860fd00c56L159-L193
